/*
SendX REST API

# Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

API version: 1.0.0
Contact: support@sendx.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sendx

import (
	"encoding/json"
	"time"
)

// checks if the ListModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListModel{}

// ListModel struct for ListModel
type ListModel struct {
	// Encrypted ID of the list
	Id *string `json:"id,omitempty"`
	// Name of the list
	Name *string `json:"name,omitempty"`
	// Type of the list representing opt-in methods (1: Single Opt-In, 2: Double Opt-In)
	Type *int32 `json:"type,omitempty"`
	// Indicates if a thank-you email should be sent
	SendThankYouMail *bool `json:"sendThankYouMail,omitempty"`
	// Name displayed as the sender in the thank-you email
	ThankYouFromName *string `json:"thankYouFromName,omitempty"`
	// Email address from which the thank-you email is sent
	ThankYouFromEmail *string `json:"thankYouFromEmail,omitempty"`
	// Subject line of the thank-you email
	ThankYouMailSubject *string `json:"thankYouMailSubject,omitempty"`
	// Plain text message body of the thank-you email
	ThankYouMailMessage *string `json:"thankYouMailMessage,omitempty"`
	// Details of the sender of the thank-you email
	ThankYouSender *string `json:"thankYouSender,omitempty"`
	// Name displayed as the sender in the confirmation email
	ConfirmFromName *string `json:"confirmFromName,omitempty"`
	// Email address from which the confirmation email is sent
	ConfirmFromEmail *string `json:"confirmFromEmail,omitempty"`
	// Subject line of the confirmation email
	ConfirmMailSubject *string `json:"confirmMailSubject,omitempty"`
	// Plain text message body of the confirmation email
	ConfirmMailMessage *string `json:"confirmMailMessage,omitempty"`
	// URL of the success page after confirmation
	ConfirmSuccessPage *string `json:"confirmSuccessPage,omitempty"`
	// Date and time when the list was created
	Created *time.Time `json:"created,omitempty"`
	// Date and time when the list was last updated
	Updated *time.Time `json:"updated,omitempty"`
	// Details of the sender of the confirmation email
	ConfirmSender NullableString `json:"confirmSender,omitempty"`
}

// NewListModel instantiates a new ListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListModel() *ListModel {
	this := ListModel{}
	return &this
}

// NewListModelWithDefaults instantiates a new ListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListModelWithDefaults() *ListModel {
	this := ListModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListModel) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListModel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ListModel) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListModel) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListModel) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListModel) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListModel) GetType() int32 {
	if o == nil || IsNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListModel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *ListModel) SetType(v int32) {
	o.Type = &v
}

// GetSendThankYouMail returns the SendThankYouMail field value if set, zero value otherwise.
func (o *ListModel) GetSendThankYouMail() bool {
	if o == nil || IsNil(o.SendThankYouMail) {
		var ret bool
		return ret
	}
	return *o.SendThankYouMail
}

// GetSendThankYouMailOk returns a tuple with the SendThankYouMail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetSendThankYouMailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendThankYouMail) {
		return nil, false
	}
	return o.SendThankYouMail, true
}

// HasSendThankYouMail returns a boolean if a field has been set.
func (o *ListModel) HasSendThankYouMail() bool {
	if o != nil && !IsNil(o.SendThankYouMail) {
		return true
	}

	return false
}

// SetSendThankYouMail gets a reference to the given bool and assigns it to the SendThankYouMail field.
func (o *ListModel) SetSendThankYouMail(v bool) {
	o.SendThankYouMail = &v
}

// GetThankYouFromName returns the ThankYouFromName field value if set, zero value otherwise.
func (o *ListModel) GetThankYouFromName() string {
	if o == nil || IsNil(o.ThankYouFromName) {
		var ret string
		return ret
	}
	return *o.ThankYouFromName
}

// GetThankYouFromNameOk returns a tuple with the ThankYouFromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetThankYouFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.ThankYouFromName) {
		return nil, false
	}
	return o.ThankYouFromName, true
}

// HasThankYouFromName returns a boolean if a field has been set.
func (o *ListModel) HasThankYouFromName() bool {
	if o != nil && !IsNil(o.ThankYouFromName) {
		return true
	}

	return false
}

// SetThankYouFromName gets a reference to the given string and assigns it to the ThankYouFromName field.
func (o *ListModel) SetThankYouFromName(v string) {
	o.ThankYouFromName = &v
}

// GetThankYouFromEmail returns the ThankYouFromEmail field value if set, zero value otherwise.
func (o *ListModel) GetThankYouFromEmail() string {
	if o == nil || IsNil(o.ThankYouFromEmail) {
		var ret string
		return ret
	}
	return *o.ThankYouFromEmail
}

// GetThankYouFromEmailOk returns a tuple with the ThankYouFromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetThankYouFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ThankYouFromEmail) {
		return nil, false
	}
	return o.ThankYouFromEmail, true
}

// HasThankYouFromEmail returns a boolean if a field has been set.
func (o *ListModel) HasThankYouFromEmail() bool {
	if o != nil && !IsNil(o.ThankYouFromEmail) {
		return true
	}

	return false
}

// SetThankYouFromEmail gets a reference to the given string and assigns it to the ThankYouFromEmail field.
func (o *ListModel) SetThankYouFromEmail(v string) {
	o.ThankYouFromEmail = &v
}

// GetThankYouMailSubject returns the ThankYouMailSubject field value if set, zero value otherwise.
func (o *ListModel) GetThankYouMailSubject() string {
	if o == nil || IsNil(o.ThankYouMailSubject) {
		var ret string
		return ret
	}
	return *o.ThankYouMailSubject
}

// GetThankYouMailSubjectOk returns a tuple with the ThankYouMailSubject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetThankYouMailSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.ThankYouMailSubject) {
		return nil, false
	}
	return o.ThankYouMailSubject, true
}

// HasThankYouMailSubject returns a boolean if a field has been set.
func (o *ListModel) HasThankYouMailSubject() bool {
	if o != nil && !IsNil(o.ThankYouMailSubject) {
		return true
	}

	return false
}

// SetThankYouMailSubject gets a reference to the given string and assigns it to the ThankYouMailSubject field.
func (o *ListModel) SetThankYouMailSubject(v string) {
	o.ThankYouMailSubject = &v
}

// GetThankYouMailMessage returns the ThankYouMailMessage field value if set, zero value otherwise.
func (o *ListModel) GetThankYouMailMessage() string {
	if o == nil || IsNil(o.ThankYouMailMessage) {
		var ret string
		return ret
	}
	return *o.ThankYouMailMessage
}

// GetThankYouMailMessageOk returns a tuple with the ThankYouMailMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetThankYouMailMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ThankYouMailMessage) {
		return nil, false
	}
	return o.ThankYouMailMessage, true
}

// HasThankYouMailMessage returns a boolean if a field has been set.
func (o *ListModel) HasThankYouMailMessage() bool {
	if o != nil && !IsNil(o.ThankYouMailMessage) {
		return true
	}

	return false
}

// SetThankYouMailMessage gets a reference to the given string and assigns it to the ThankYouMailMessage field.
func (o *ListModel) SetThankYouMailMessage(v string) {
	o.ThankYouMailMessage = &v
}

// GetThankYouSender returns the ThankYouSender field value if set, zero value otherwise.
func (o *ListModel) GetThankYouSender() string {
	if o == nil || IsNil(o.ThankYouSender) {
		var ret string
		return ret
	}
	return *o.ThankYouSender
}

// GetThankYouSenderOk returns a tuple with the ThankYouSender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetThankYouSenderOk() (*string, bool) {
	if o == nil || IsNil(o.ThankYouSender) {
		return nil, false
	}
	return o.ThankYouSender, true
}

// HasThankYouSender returns a boolean if a field has been set.
func (o *ListModel) HasThankYouSender() bool {
	if o != nil && !IsNil(o.ThankYouSender) {
		return true
	}

	return false
}

// SetThankYouSender gets a reference to the given string and assigns it to the ThankYouSender field.
func (o *ListModel) SetThankYouSender(v string) {
	o.ThankYouSender = &v
}

// GetConfirmFromName returns the ConfirmFromName field value if set, zero value otherwise.
func (o *ListModel) GetConfirmFromName() string {
	if o == nil || IsNil(o.ConfirmFromName) {
		var ret string
		return ret
	}
	return *o.ConfirmFromName
}

// GetConfirmFromNameOk returns a tuple with the ConfirmFromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetConfirmFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmFromName) {
		return nil, false
	}
	return o.ConfirmFromName, true
}

// HasConfirmFromName returns a boolean if a field has been set.
func (o *ListModel) HasConfirmFromName() bool {
	if o != nil && !IsNil(o.ConfirmFromName) {
		return true
	}

	return false
}

// SetConfirmFromName gets a reference to the given string and assigns it to the ConfirmFromName field.
func (o *ListModel) SetConfirmFromName(v string) {
	o.ConfirmFromName = &v
}

// GetConfirmFromEmail returns the ConfirmFromEmail field value if set, zero value otherwise.
func (o *ListModel) GetConfirmFromEmail() string {
	if o == nil || IsNil(o.ConfirmFromEmail) {
		var ret string
		return ret
	}
	return *o.ConfirmFromEmail
}

// GetConfirmFromEmailOk returns a tuple with the ConfirmFromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetConfirmFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmFromEmail) {
		return nil, false
	}
	return o.ConfirmFromEmail, true
}

// HasConfirmFromEmail returns a boolean if a field has been set.
func (o *ListModel) HasConfirmFromEmail() bool {
	if o != nil && !IsNil(o.ConfirmFromEmail) {
		return true
	}

	return false
}

// SetConfirmFromEmail gets a reference to the given string and assigns it to the ConfirmFromEmail field.
func (o *ListModel) SetConfirmFromEmail(v string) {
	o.ConfirmFromEmail = &v
}

// GetConfirmMailSubject returns the ConfirmMailSubject field value if set, zero value otherwise.
func (o *ListModel) GetConfirmMailSubject() string {
	if o == nil || IsNil(o.ConfirmMailSubject) {
		var ret string
		return ret
	}
	return *o.ConfirmMailSubject
}

// GetConfirmMailSubjectOk returns a tuple with the ConfirmMailSubject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetConfirmMailSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmMailSubject) {
		return nil, false
	}
	return o.ConfirmMailSubject, true
}

// HasConfirmMailSubject returns a boolean if a field has been set.
func (o *ListModel) HasConfirmMailSubject() bool {
	if o != nil && !IsNil(o.ConfirmMailSubject) {
		return true
	}

	return false
}

// SetConfirmMailSubject gets a reference to the given string and assigns it to the ConfirmMailSubject field.
func (o *ListModel) SetConfirmMailSubject(v string) {
	o.ConfirmMailSubject = &v
}

// GetConfirmMailMessage returns the ConfirmMailMessage field value if set, zero value otherwise.
func (o *ListModel) GetConfirmMailMessage() string {
	if o == nil || IsNil(o.ConfirmMailMessage) {
		var ret string
		return ret
	}
	return *o.ConfirmMailMessage
}

// GetConfirmMailMessageOk returns a tuple with the ConfirmMailMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetConfirmMailMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmMailMessage) {
		return nil, false
	}
	return o.ConfirmMailMessage, true
}

// HasConfirmMailMessage returns a boolean if a field has been set.
func (o *ListModel) HasConfirmMailMessage() bool {
	if o != nil && !IsNil(o.ConfirmMailMessage) {
		return true
	}

	return false
}

// SetConfirmMailMessage gets a reference to the given string and assigns it to the ConfirmMailMessage field.
func (o *ListModel) SetConfirmMailMessage(v string) {
	o.ConfirmMailMessage = &v
}

// GetConfirmSuccessPage returns the ConfirmSuccessPage field value if set, zero value otherwise.
func (o *ListModel) GetConfirmSuccessPage() string {
	if o == nil || IsNil(o.ConfirmSuccessPage) {
		var ret string
		return ret
	}
	return *o.ConfirmSuccessPage
}

// GetConfirmSuccessPageOk returns a tuple with the ConfirmSuccessPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetConfirmSuccessPageOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmSuccessPage) {
		return nil, false
	}
	return o.ConfirmSuccessPage, true
}

// HasConfirmSuccessPage returns a boolean if a field has been set.
func (o *ListModel) HasConfirmSuccessPage() bool {
	if o != nil && !IsNil(o.ConfirmSuccessPage) {
		return true
	}

	return false
}

// SetConfirmSuccessPage gets a reference to the given string and assigns it to the ConfirmSuccessPage field.
func (o *ListModel) SetConfirmSuccessPage(v string) {
	o.ConfirmSuccessPage = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ListModel) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ListModel) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ListModel) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ListModel) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModel) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ListModel) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ListModel) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetConfirmSender returns the ConfirmSender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListModel) GetConfirmSender() string {
	if o == nil || IsNil(o.ConfirmSender.Get()) {
		var ret string
		return ret
	}
	return *o.ConfirmSender.Get()
}

// GetConfirmSenderOk returns a tuple with the ConfirmSender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListModel) GetConfirmSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfirmSender.Get(), o.ConfirmSender.IsSet()
}

// HasConfirmSender returns a boolean if a field has been set.
func (o *ListModel) HasConfirmSender() bool {
	if o != nil && o.ConfirmSender.IsSet() {
		return true
	}

	return false
}

// SetConfirmSender gets a reference to the given NullableString and assigns it to the ConfirmSender field.
func (o *ListModel) SetConfirmSender(v string) {
	o.ConfirmSender.Set(&v)
}
// SetConfirmSenderNil sets the value for ConfirmSender to be an explicit nil
func (o *ListModel) SetConfirmSenderNil() {
	o.ConfirmSender.Set(nil)
}

// UnsetConfirmSender ensures that no value is present for ConfirmSender, not even an explicit nil
func (o *ListModel) UnsetConfirmSender() {
	o.ConfirmSender.Unset()
}

func (o ListModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.SendThankYouMail) {
		toSerialize["sendThankYouMail"] = o.SendThankYouMail
	}
	if !IsNil(o.ThankYouFromName) {
		toSerialize["thankYouFromName"] = o.ThankYouFromName
	}
	if !IsNil(o.ThankYouFromEmail) {
		toSerialize["thankYouFromEmail"] = o.ThankYouFromEmail
	}
	if !IsNil(o.ThankYouMailSubject) {
		toSerialize["thankYouMailSubject"] = o.ThankYouMailSubject
	}
	if !IsNil(o.ThankYouMailMessage) {
		toSerialize["thankYouMailMessage"] = o.ThankYouMailMessage
	}
	if !IsNil(o.ThankYouSender) {
		toSerialize["thankYouSender"] = o.ThankYouSender
	}
	if !IsNil(o.ConfirmFromName) {
		toSerialize["confirmFromName"] = o.ConfirmFromName
	}
	if !IsNil(o.ConfirmFromEmail) {
		toSerialize["confirmFromEmail"] = o.ConfirmFromEmail
	}
	if !IsNil(o.ConfirmMailSubject) {
		toSerialize["confirmMailSubject"] = o.ConfirmMailSubject
	}
	if !IsNil(o.ConfirmMailMessage) {
		toSerialize["confirmMailMessage"] = o.ConfirmMailMessage
	}
	if !IsNil(o.ConfirmSuccessPage) {
		toSerialize["confirmSuccessPage"] = o.ConfirmSuccessPage
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if o.ConfirmSender.IsSet() {
		toSerialize["confirmSender"] = o.ConfirmSender.Get()
	}
	return toSerialize, nil
}

type NullableListModel struct {
	value *ListModel
	isSet bool
}

func (v NullableListModel) Get() *ListModel {
	return v.value
}

func (v *NullableListModel) Set(val *ListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListModel(val *ListModel) *NullableListModel {
	return &NullableListModel{value: val, isSet: true}
}

func (v NullableListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


